import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import Axios from 'axios';
import styles from '@/styles/admin_articles.module.css';
import Input from '@/components/form/Input';
import InputBody from '@/components/form/InputBody';
import InputRadio from '@/components/form/InputRadio';
import Buttons from '@/components/form/Buttons';

export default function createArticle() {

    const url = "http://localhost:8080/api/articles";

    const [article, setarticle] = useState({
        kb_title: undefined,
        kb_body: undefined,
        kb_liked_count: undefined,
        kb_published: undefined,
        kb_suggestion: undefined,
        kb_featured: undefined,
        kb_author_email: undefined,
        kb_published_date: undefined,
    });

    const inputOptions = [
        { value: true, text: 'Sim' },
        { value: false, text: 'Não' },
    ];

    const handleChange = (event) => {
        const { name, value } = event.target;

        setarticle({
            ...article,
            [name]: value
        });
    };

    const handleCreatearticle = async () => {
        try {
            const response = await Axios.post(url, { article });
            // console.log(response.data);
        } catch (error) {
            console.error('Erro ao criar o artigo:', error);
        }
    };

    return (
        <>
            <Head>
                <title>Novo artigo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <header>
                <NavAdmin />
            </header>

            <main className={styles.background_img}>
                <h2>Novo artigo</h2>

                <div className={styles.form_wrapper}>
                    <form method='POST'>
                        <Input
                            type='text'
                            text='Título'
                            name='kb_title'
                            placeholder='Digite...'
                            value={article.kb_title}
                            eventOnChange={handleChange}
                            required={true}
                        />

                        <InputBody
                            text='Corpo'
                            name='kb_body'
                            placeholder='Digite o corpo do seu artigo...'
                            value={article.kb_body}
                            eventOnChange={handleChange}
                        />

                        <hr></hr>

                        <Input
                            type='email'
                            text='E-mail do autor'
                            name='kb_author_email'
                            placeholder='Digite...'
                            value={article.kb_author_email}
                            eventOnChange={handleChange}
                            required={true}
                        />

                        <InputRadio
                            titulo='Destaque?'
                            name='kb_featured'
                            options={inputOptions}
                            eventOnChange={handleChange}
                        />

                        <Buttons 
                            href='/admin/articles'
                            eventOnClick={handleCreatearticle}
                        />
                    </form>
                </div>
            </main>
        </>
    )
}