import Head from "next/head";
import NavHome from '../../components/NavHome';
import styles from '../../styles/article.module.css';
import { useState, useEffect } from 'react';
import { useRouter } from "next/router";
import Axios from 'axios';

export default function Article() {
    const URL = "http://localhost:8080/api/articles/";
    const [article, setArticle] = useState([]);
    const router = useRouter();
    const [pid] = useState(router.query.pid);

    useEffect(() => {
        const getArticle = async () => {
            try {
                const response = await Axios.get(URL + pid);
                setArticle(response.data);
            } catch (error) {
                console.error('Erro ao buscar o artigo:', error);
            }
        };
        getArticle();
    }, []);

    return (
        <>
            <Head>
                <title>{article.kb_title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <header>
                <NavHome />
            </header>

            <main className={styles.background_image}>
                <div id={styles.section} className={styles.background_opacity}>
                    <h2 id={styles.titulo}>{article.kb_title}</h2>
                    <div id={styles.conteiner} className={styles.text_conteiner}>
                        <p id={styles.texto}>{article.kb_body}</p>
                    </div>
                </div>

                <div className={styles.author_information}>
                    <span className={styles.author_email}>{article.kb_author_email}</span>
                    <span className={styles.published_date}>{article.kb_published_date}</span>
                </div>
            </main>

        </>

    )

}



