import NavHome from '../components/NavHome'
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Axios from 'axios';

export default function Home() {
    const [articles, setArticles] = useState([]);
    const [destaques, setDestaques] = useState([]);

    const URL = "http://localhost:8080/api/articles";

    useEffect(() => {
        const getAllArticles = async () => {
            try {
                const response = await Axios.get(URL);
                setArticles(response.data);
                setDestaques(response.data.filter((article) => article.kb_featured === true));
            } catch (error) {
                console.error('Erro ao buscar os artigos:', error);
            }
        };

        getAllArticles();
    }, []);

    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <NavHome />

            <main className={styles.main}>

                <h2 className={styles.h2}>ARTIGOS DESTAQUE</h2>
                <section className={styles.section_artigos}>

                    {
                        destaques.map((article, index) => (
                            <article key={index} className={styles.card_artigo}>
                                <Link href={`/article/${article._id}`} className={styles.link_artigo}>
                                    <h3 className={styles.titulo_artigo}>{article.kb_title}</h3>
                                    <p className={styles.texto_artigo}>{article.kb_body}</p>
                                </Link>
                            </article>
                        ))
                    }

                </section>

                <h2 className={styles.h2}>TODOS ARTIGOS</h2>
                <section className={styles.section_artigos}>

                    {
                        articles.map((article, index) => (
                            <article key={index} className={styles.card_artigo}>
                                <Link href={`/article/${article._id}`} className={styles.link_artigo}>
                                    <h3 className={styles.titulo_artigo}>{article.kb_title}</h3>
                                    <p className={styles.texto_artigo}>{article.kb_body}</p>
                                </Link>
                            </article>
                        ))
                    }

                </section>

            </main>

            <footer className={styles.footer}>
                <p>Alysson Pereira - Gianfranco Keller - Gabriel Milanez - Lucas Borges</p>
            </footer>
        </>
    );
}


