import Head from 'next/head';
import Input from '@/components/form/Input';
import { useState } from 'react';
import styles from '@/styles/form.module.css';
import axios from 'axios';

export default function Home() {
    const [email, setEmail] = useState('');
    const [senha, setSenha] = useState('');
    const [message, setMessage] = useState('');

    const handleChange = (event) => {
        const { name, value } = event.target;

        if (name == 'email') {
            setEmail(value);
        } else {
            setSenha(value);
        }
    }

    const handleSubmit = async (event) => {
        event.preventDefault();
        const user = { email: email, password: senha };

        await axios.post('http://localhost:8080/api/users/login', user).then(res => {
            sessionStorage.setItem('user', JSON.stringify(res.data.user));
            sessionStorage.setItem('admin', res.data.admin);

            if (res.data.admin) {
                window.location.href = '/admin';
            }
            else {
                window.location.href = '/';
            }

        }).catch(err => {
            console.error(err);
            setMessage('Usuário ou senha inválidos!');
            setTimeout(() => {
                setMessage('');
            }, 3000);
        });
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className={styles.login_wrapper}>
                <h1 className={styles.h1}>Login</h1>

                <div className={styles.login_message}>
                    {message}
                </div>

                <form action='/admin' method="POST">
                    <Input
                        type='text'
                        name='email'
                        text='E-mail'
                        eventOnChange={handleChange}
                        placeholder='Digite seu e-mail'
                        value={email}
                    />

                    <Input
                        type='password'
                        name='senha'
                        text='Senha'
                        eventOnChange={handleChange}
                        placeholder='Digite sua senha'
                        value={senha}
                    />

                    <button className={styles.btn_enviar} type='submit' onClick={handleSubmit}>enviar</button>
                </form>
            </main>
        </>
    )
}


