import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/admin.module.css'

export default function adminPage() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.admin_main}>
        <div className={styles.admin_conteiner}>
          <div>
            <Link className={styles.admin_link} href="/admin/articles">Ver artigos</Link>
          </div>

          <div>
            <Link className={styles.admin_link} href={"/admin/users"}>Ver usuários</Link>
          </div>
        </div>
      </main>
    </>
  )
}


